application: cs253
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# URLS and apps
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: templates/css

- url: /img
  static_dir: templates/img
  #static_files:

#Main
- url: /
  script: main.app

#rot13 work
- url: /unit2/w21.*
  script: apps.rot13.rot13.app

#Login work
- url: /unit2/w22.*
  script: apps.login.login.app

#Login Wellcome
- url: /unit2/wellcome.*
  script: apps.login.login.app

#Ascii work
- url: /ascii.*
  script: apps.ascii.ascii.app

#Blog work
- url: /blog.*
  script: apps.blog.blog.app

- url: /blog/(.*)
  script: apps.blog.blog.app

- url: /.*
  script: main.app

# Libraries!
libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest